spring.application.name=WarehouseAllocationApplication

spring.datasource.url=jdbc:mysql://localhost:3306/warehouse_db?useSSL=false

spring.datasource.username=root

spring.datasource.password=Praveen@123

spring.jpa.generate-ddl=true

spring.jpa.hibernate.ddl-auto = update

spring.jpa.show-sql: true
 
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration